### ISSUE TITLE
Fix resizing issues

### ISSUE THREAD

**Issue by MatthewDaggitt** [MatthewDaggitt/AshCalc#18]
See #17 for details and screenshots

**Comment by wmoreland** [comment]
At least as a temporary work-around, the figsize could be reduced on line 808 in results_frame.py. Rather arbitrary values of (4.7, 2.8) work for me while using the "clam" theme:
![2020-01-16-100536_1225x664_scrot](https://user-images.githubusercontent.com/16152742/72509497-fb68bc00-3847-11ea-96a0-88215f4b270e.png)

**Comment by MatthewDaggitt** [comment]
Sorry, taken a while to fix this. Better late than never I guess. Turns out the offending line was:
```python
# Terrible kludgy hack to force the app to stay the right size
# Need to work out how to remove
self.grid_propagate(False)
```
I must have fixed this problem and forgot to remove it, as when I remove the line it seems to work fine on both Windows and Ubuntu.
